function [...
    dCGM_extended_day_actual_out,...
    dSMBG_extended_day_out,...
    dU_extended_day_out,...
    bolus_extended_day_out,...
    basal_extended_day_out,...
    meal_mgpmin_extended_day_out,...
    dates_extended_day_out...
    ] = reconcileDates(...
    dCGM_extended_day_actual,...
    datesValidCGM_extended_day,...
    dSMBG_extended_day,...
    dU_extended_day,...
    bolus_extended_day,...
    basal_extended_day,...
    meal_mgpmin_extended_day,...
    dates_extended_day...
    )


dCGM_extended_day_actual_out = [];
dSMBG_extended_day_out = [];
dU_extended_day_out = [];
bolus_extended_day_out = [];
basal_extended_day_out = [];
meal_mgpmin_extended_day_out = [];
hypotreat_mgpmin_extended_day_out = [];
dates_extended_day_out = [];

minday = min(dates_extended_day(1,1), datesValidCGM_extended_day(1,1));
maxday = max(dates_extended_day(end,end), datesValidCGM_extended_day(end,end));
for day = minday:maxday
    
    ind1 = find(dates_extended_day(1,:) == day);
    ind2 = find(datesValidCGM_extended_day(1,:) == day);
    
    if ~isempty(ind1) && ~isempty(ind2)
        
        if length(ind1) > 1 || length(ind2) > 1
            disp('FIX: error in reconcileDates')
            pause
        end
        
        dCGM_extended_day_actual_out = [dCGM_extended_day_actual_out dCGM_extended_day_actual(:,ind2)];
        dSMBG_extended_day_out = [dSMBG_extended_day_out dSMBG_extended_day(:,ind1)];
        dU_extended_day_out = [dU_extended_day_out dU_extended_day(:,ind1)];
        bolus_extended_day_out = [bolus_extended_day_out bolus_extended_day(:,ind1)];
        basal_extended_day_out = [basal_extended_day_out basal_extended_day(:,ind1)];
        meal_mgpmin_extended_day_out = [meal_mgpmin_extended_day_out meal_mgpmin_extended_day(:,ind1)];
        dates_extended_day_out = [dates_extended_day_out dates_extended_day(:,ind1)];
        
    end
    
end